<?php


$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Siden skal ikke indekseres af robotter';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Siden indekseres af robotter';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Synlighed overfor robotter';

$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Meta tags opdateret';

$_COS_LANG_MODULE['meta_always_visible'] = 'Robot tag for satte domæne navne er altid synlig';
