<?php


// Translation of file /modules/meta/model.meta.inc

$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Not visible for robots';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Visible for robots';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Update robots visibility';

// Translation of file /modules/meta/meta/model.meta.inc


// Translation of file /modules/meta/meta/index.php

$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot visibility updated';

// Translation of file /modules/meta/index.php

$_COS_LANG_MODULE['meta_always_visible'] = 'Robot visibility for add-on domain name is always visible';
