<?php


$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Visible for robots';
$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Not visible for robots';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Update robots visibility';

$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot visibility updated';

$_COS_LANG_MODULE['meta_always_visible'] = 'Robot visibility for add-on domain name is always visible';
