<?php

$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Ikke synlig for roboter';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Synlig for roboter';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Oppdater roboter synlighet';
$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot synlighet oppdatert';
$_COS_LANG_MODULE['meta_always_visible'] = 'Robot synlighet for add-on domenenavn er alltid synlig';
