<?php

$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Nicht sichtbar für Roboter';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Sichtbar für Roboter';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Update-Roboter Sichtbarkeit';
$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot Sichtbarkeit aktualisiert';
$_COS_LANG_MODULE['meta_always_visible'] = 'Robot Sichtbarkeit für Add-on Domain-Namen ist immer sichtbar';
