<?php

$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Ei näkyvissä robotteja';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Näkyvissä robotit';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Päivitys robotit näkyvyys';
$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot näkyvyys päivitetty';
$_COS_LANG_MODULE['meta_always_visible'] = 'Robot näkyvyyttä add-on verkkotunnus on aina näkyvissä';
