<?php

$_COS_LANG_MODULE['meta_meta_in_visible_for_robots'] = 'Inte synlig för robotar';
$_COS_LANG_MODULE['meta_meta_visible_for_robots'] = 'Synlig för robotar';
$_COS_LANG_MODULE['meta_robots_legend'] = 'Uppdatering av robotar synlighet';
$_COS_LANG_MODULE['meta_meta_updated_action'] = 'Robot synlighet uppdateras';
$_COS_LANG_MODULE['meta_always_visible'] = 'Robot synlighet för utökning domännamn är alltid synlig';
